### PR TITLE
CBOR Library Security Comparisons (March 2020)

### PR DESCRIPTION
**Pull request by x448**
Newer malformed CBOR data causes "fatal: out of memory" error in all released versions of ugorji/go (1.1.0 - 1.1.7) and also with the last commit of ugorji/go.  

Only 1 decode attempt of less than 10 bytes is needed to exhaust memory using all versions of ugorji/go.

Prior security comparisons used malformed CBOR data from Sep 2019 (found by oasislabs) which only affects some versions of ugorji/go.

By comparison, fxamacker/cbor correctly rejects malformed CBOR data.

Updates https://github.com/fxamacker/cbor/issues/208

### CODE REVIEW

**Comment by x448** [comment]
@fxamacker don't merge yet, there's one more security comparison table.

**Comment by x448** [comment]
@fxamacker please review and merge when ready.  There's only 1 error message using the newer malformed CBOR data.

**Comment by x448** [comment]
@fxamacker all done. Minor tweaks as discussed, no other changes.

**Comment by fxamacker** [comment]
@x448 Looks good!  Can you also update the slideshow with the new security comparison please?

**Comment by fxamacker** [comment]
LGTM :+1:

**Pull request merged**
